# ============================================================================
# Script: appV3.R
# Author: Noah Muscat, Simeone Marino
# Date: 2025-04-04
# Description:
#   R Shiny application for visualizing pre-processed behavioral data
#   generated by the 'RBB_Data_Processor' batch script.
#   Reads processed files (Files 3, 6, 7, 8, WheelMovement) from a structured
#   directory and displays tables and plots.
#
# Data Source:
#   - Expects processed_data_dir to contain experiment_XX/cohort_XX subfolders.
#   - Looks for files named like [basename]_FileX.csv or [basename]_WheelMovement.csv
#     within the cohort folders.
#
# Dependencies: shiny, DT, data.table, dplyr, tidyr, lubridate, stringr, ggplot2, shinycssloaders
# ============================================================================

# --- Load Required Libraries ---
# message("Loading required packages...") # Less verbose for Shiny app
required_packages <- c("shiny", "DT", "data.table", "dplyr", "tidyr", "lubridate", "stringr", "ggplot2", "shinycssloaders")
for (pkg in required_packages) { library(pkg, character.only = TRUE) }

# --- Global Parameters ---

# Path to the *main* directory where the BATCH SCRIPT saved its output files
# ** Use absolute path **
processed_data_dir <- "/nfs/turbo/umms-brendonw/RBB_Data_Cleaned" # <<< UPDATE if different from batch script output

# Fixed descriptive labels for the 8 digital channels (0-7)
# Should match the labels used in the batch script's output columns
CHANNEL_LABELS <- c(
  "Water_1_Beambreak",  # Channel 0
  "Water_2_Beambreak",  # Channel 1
  "Food_1_Beambreak",   # Channel 2
  "Food_2_Beambreak",   # Channel 3
  "Water_1_Dispense",   # Channel 4
  "Water_2_Dispense",   # Channel 5
  "Food_1_Dispense",    # Channel 6
  "Food_2_Dispense"     # Channel 7
)

# Expected column names for binned data (using Measure_Label format from batch script)
# Used for plot loops
COUNT_COL_NAMES <- paste("Count", CHANNEL_LABELS, sep = "_")
# DURATION_COL_NAMES <- paste("TotalDuration", CHANNEL_LABELS, sep = "_") # Keep for future use

# --- UI Definition ---
ui <- fluidPage(
  tags$head(
    tags$style(HTML("
      .shiny-input-container, .shiny-input-container > label {
        font-size: 14px !important;
        font-family: Arial, sans-serif !important;
      }
      /* Optional: Style for spinner */
      .shiny-spinner-output-container { min-height: 300px; }
    "))
  ),
  titlePanel("RBB Experiment Portal (Processed Data Viewer)"),
  
  sidebarLayout(
    sidebarPanel(
      width = 3, # Make sidebar slightly narrower
      selectInput("experiment", "Experiment", choices = c("Loading..." = "")),
      selectInput("cohort", "Cohort", choices = c("Loading..." = "")),
      uiOutput("rat_select_ui"), # Renamed UI output ID
      radioButtons("date_choice", "Select Date Option:",
                   choices = c("All Available Dates" = "all", "Single Date" = "single", "Date Range" = "range"),
                   selected = "all"),
      uiOutput("date_input_ui") # Renamed UI output ID
    ),
    mainPanel(
      width = 9, # Make main panel wider
      tabsetPanel(
        type = "tabs",
        tabPanel("Daily Plots (Counts)", withSpinner(plotOutput("daily_plots_output"))), # Combined plots
        tabPanel("Hourly Plots (Counts)", withSpinner(plotOutput("hourly_plots_output"))), # Combined plots
        tabPanel("Minute Bin Data (File 6)",
                 withSpinner(DT::dataTableOutput('tbl_minute')),
                 downloadButton('download_minute', 'Download Minute Data')
        ),
        tabPanel("Raw States (File 3)",
                 withSpinner(DT::dataTableOutput('tbl_raw_states')), # Renamed output ID
                 downloadButton('download_file3', 'Download Raw States Data') # Renamed download ID
        ),
        tabPanel("Wheel Movement", # New Tab
                 withSpinner(DT::dataTableOutput('tbl_wheel')),
                 downloadButton('download_wheel', 'Download Wheel Data')
        ),
        tabPanel("IN PROGRESS - Actigraphy", p("Actigraphy analysis module pending.")) # Kept placeholder
      )
    )
  ),
  div("RBB App Version: V.3.0-Refactored", align = "center") # Updated version
)

# --- Server Logic ---
server <- function(input, output, session) {
  
  # --- File Discovery ---
  
  # Reactive to scan the processed data directory and build metadata
  all_processed_files_info <- reactive({
    message("Scanning processed data directory:", processed_data_dir)
    req(dir.exists(processed_data_dir))
    
    # Define expected file suffixes
    file_suffixes <- c("_File3.csv", "_File4.csv", "_File5.csv", "_File6.csv", "_File7.csv", "_File8.csv", "_WheelMovement.csv")
    pattern_suffix <- paste(gsub("\\.", "\\\\.", file_suffixes), collapse = "|") # Create OR pattern for suffixes
    # Pattern to capture base filename and suffix
    full_pattern <- paste0("(RBB\\d{2}_\\d{8}_\\d{6})(", pattern_suffix, ")$")
    
    all_files <- list.files(path = processed_data_dir,
                            pattern = "\\.csv$", # Find all CSVs first
                            recursive = TRUE,
                            full.names = TRUE)
    
    # Filter for files matching our specific processed file patterns
    processed_files <- all_files[grepl(full_pattern, basename(all_files))]
    
    if (length(processed_files) == 0) {
      showNotification("No processed data files found in the specified directory structure.", type = "warning")
      return(data.table()) # Return empty data.table
    }
    
    # Use lapply and rbindlist for efficient parsing
    file_info_list <- lapply(processed_files, function(file_path) {
      file_name <- basename(file_path)
      path_parts <- strsplit(dirname(file_path), .Platform$file.sep)[[1]]
      
      # Attempt to extract metadata from filename and path
      base_match <- stringr::str_match(file_name, "^(RBB\\d{2}_\\d{8}_\\d{6})_(File[3-8]|WheelMovement)\\.csv$")
      exp_match <- stringr::str_extract(file_path, "experiment_\\d{2}")
      cohort_match <- stringr::str_extract(file_path, "cohort_\\d{2}")
      
      if (!any(is.na(base_match)) && !is.na(exp_match) && !is.na(cohort_match)) {
        # Parse base filename parts
        base_name_parts <- stringr::str_match(base_match[1, 2], "^(RBB\\d{2})_(\\d{8})_(\\d{6})$")
        rat_id <- base_name_parts[1, 2]
        date_str <- base_name_parts[1, 3]
        time_str <- base_name_parts[1, 4]
        file_type <- base_match[1, 3] # e.g., "File3", "WheelMovement"
        
        return(data.table(
          file_path = file_path,
          experiment_id = gsub("experiment_", "", exp_match),
          cohort_id = gsub("cohort_", "", cohort_match),
          rat_id = rat_id,
          date = ymd(date_str, quiet = TRUE), # Suppress parsing warnings
          time_str = time_str,
          file_type = file_type
        ))
      } else {
        return(NULL) # Skip files that don't match expected name/path structure
      }
    })
    
    # Combine valid info into a single data.table
    valid_info <- rbindlist(Filter(Negate(is.null), file_info_list))
    
    if(nrow(valid_info) == 0) {
      showNotification("No files matched the expected naming/path structure (e.g., .../experiment_XX/cohort_XX/RBBXX_YYYYMMDD_HHMMSS_FileN.csv).", type = "warning", duration=15)
    } else {
      message("Found ", nrow(valid_info), " processed files matching structure.")
    }
    
    return(valid_info)
  })
  
  # --- Populate UI Selectors ---
  
  observe({
    req(all_processed_files_info())
    choices <- unique(all_processed_files_info()$experiment_id)
    updateSelectInput(session, "experiment", choices = sort(choices))
  })
  
  observe({
    req(input$experiment, all_processed_files_info())
    choices <- unique(all_processed_files_info()[experiment_id == input$experiment, ]$cohort_id)
    updateSelectInput(session, "cohort", choices = sort(choices))
  })
  
  output$rat_select_ui <- renderUI({
    req(input$experiment, input$cohort, all_processed_files_info())
    choices <- unique(all_processed_files_info()[experiment_id == input$experiment & cohort_id == input$cohort, ]$rat_id)
    selectInput("rat", label = "Rat ID", choices = sort(choices), selected = first(sort(choices)))
  })
  
  available_dates <- reactive({
    req(input$experiment, input$cohort, input$rat, all_processed_files_info())
    # Ensure date column exists and has non-NA values
    info <- all_processed_files_info()[experiment_id == input$experiment & cohort_id == input$cohort & rat_id == input$rat & !is.na(date), ]
    sort(unique(info$date))
  })
  
  output$date_input_ui <- renderUI({
    dates <- available_dates()
    req(length(dates) > 0) # Require at least one valid date
    
    if (input$date_choice == "single") {
      selectInput("single_date", "Select Date", choices = format(dates, "%Y-%m-%d"), selected = format(last(dates), "%Y-%m-%d"))
    } else if (input$date_choice == "range") {
      dateRangeInput("date_range",
                     label = "Select Date Range",
                     start = first(dates), end = last(dates),
                     min = first(dates), max = last(dates))
    } else { # "all" selected
      NULL # No date input needed for 'all'
    }
  })
  
  # --- Data Loading Reactives ---
  
  # Helper reactive to filter file list based on core selections
  selected_files_base <- reactive({
    req(input$experiment, input$cohort, input$rat, input$date_choice, all_processed_files_info())
    info <- all_processed_files_info()
    req(nrow(info) > 0) # Ensure info is not empty
    
    # Filter by Exp/Cohort/Rat
    filtered_info <- info[experiment_id == input$experiment & cohort_id == input$cohort & rat_id == input$rat, ]
    req(nrow(filtered_info) > 0)
    
    # Filter by Date
    if (input$date_choice == "single") {
      req(input$single_date)
      selected_date <- ymd(input$single_date, quiet=TRUE)
      req(!is.na(selected_date))
      filtered_info <- filtered_info[date == selected_date, ]
    } else if (input$date_choice == "range") {
      req(input$date_range)
      start_date <- ymd(input$date_range[1], quiet=TRUE)
      end_date <- ymd(input$date_range[2], quiet=TRUE)
      req(!is.na(start_date), !is.na(end_date))
      filtered_info <- filtered_info[date >= start_date & date <= end_date, ]
    } # No date filter needed for 'all'
    
    if(nrow(filtered_info) == 0){
      showNotification("No processed files found for the selected criteria.", type="warning")
    }
    
    return(filtered_info)
  })
  
  # Helper function to read selected files of a specific type
  # Consider adding memoise here if loading is slow
  # cached_fread <- memoise(fread) # Example if memoising fread
  load_selected_files <- function(file_type_short) {
    base_info <- selected_files_base()
    req(nrow(base_info) > 0)
    
    # Determine suffix based on short type
    file_suffix <- switch(file_type_short,
                          "File3" = "_File3.csv",
                          "File6" = "_File6.csv",
                          "File7" = "_File7.csv",
                          "File8" = "_File8.csv",
                          "Wheel" = "_WheelMovement.csv",
                          stop("Invalid file type requested") # Should not happen
    )
    
    # Filter for the specific file type needed
    files_to_load <- base_info[file_type == file_type_short, ]$file_path
    
    req(length(files_to_load) > 0) # Ensure files of the required type exist
    
    message("Loading ", length(files_to_load), " '", file_type_short, "' file(s)...")
    
    # Read files and combine
    tryCatch({
      data_list <- lapply(files_to_load, data.table::fread)
      combined_data <- data.table::rbindlist(data_list, fill = TRUE)
      
      # Attempt to convert Timestamp/BinStartTime back to POSIXct if read as character
      time_cols <- intersect(c("Timestamp", "BinStartTime"), names(combined_data))
      for(t_col in time_cols){
        # Check if it's character (fread might guess sometimes) or needs tz conversion
        if(is.character(combined_data[[t_col]])) {
          # Try parsing common formats fwrite might produce (incl. ISO8601 Z)
          combined_data[, (t_col) := lubridate::parse_date_time(get(t_col), orders = c("Ymd HMS", "Ymd H:M:S", "Y-m-d H:M:OS", "Ymd GMS"), tz="UTC")] # Assume fwrite outputs UTC
        }
        # Ensure correct display timezone if desired (e.g., force to UTC or local)
        # lubridate::with_tz(combined_data[[t_col]], "UTC") # Example
      }
      
      # Convert Count columns read by fread back to integer if they became numeric
      count_col_names_in_data <- grep("^Count_", names(combined_data), value=TRUE)
      if(length(count_col_names_in_data) > 0){
        for(c_col in count_col_names_in_data){
          if(is.numeric(combined_data[[c_col]]) && !is.integer(combined_data[[c_col]])){
            combined_data[, (c_col) := as.integer(get(c_col))]
          }
        }
      }
      
      message("Loaded data dimensions: ", nrow(combined_data), " rows, ", ncol(combined_data), " cols.")
      return(combined_data)
    }, error = function(e) {
      showNotification(paste("Error reading/combining", file_type_short, "files:", e$message), type="error")
      return(data.table()) # Return empty on error
    })
  }
  
  # Specific reactives for each data type
  loaded_file3 <- reactive({ load_selected_files("File3") })
  loaded_file6 <- reactive({ load_selected_files("File6") })
  loaded_file7 <- reactive({ load_selected_files("File7") })
  loaded_file8 <- reactive({ load_selected_files("File8") })
  loaded_wheel <- reactive({ load_selected_files("WheelMovement") })
  
  
  # --- Render Outputs ---
  
  # == Plotting Tabs ==
  # Combined plot output for Daily Counts
  output$daily_plots_output <- renderPlot({
    data_daily <- loaded_file8()
    req(nrow(data_daily) > 0)
    
    # Ensure BinStartTime is Date for plotting clarity
    data_daily[, BinStartTime := as.Date(BinStartTime)] 
    
    # Convert to long format for ggplot faceting
    data_long <- tryCatch(melt(data_daily, 
                               id.vars = "BinStartTime", 
                               measure.vars = patterns("^Count_"), 
                               variable.name = "Label", value.name = "Count"),
                          error = function(e) NULL) # Handle melt errors if columns missing
    req(data_long)
    
    # Clean up label names for plot facets
    data_long[, Label := gsub("Count_", "", Label)]
    
    ggplot(data_long, aes(x = BinStartTime, y = Count)) +
      geom_col(fill = "steelblue") + # Use geom_col for bar chart
      facet_wrap(~ Label, scales = "free_y", ncol=2) + # Facet by label, free y-axis
      labs(title = "Total Daily Beambreak Counts per Channel",
           x = "Date", y = "Total Count") +
      theme_bw(base_size = 10) + # Adjust base size for readability
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            strip.text = element_text(size = 8)) + # Smaller facet titles
      scale_x_date(date_breaks = "1 day", date_labels = "%Y-%m-%d")
  })
  
  # Combined plot output for Hourly Counts
  output$hourly_plots_output <- renderPlot({
    data_hourly <- loaded_file7()
    req(nrow(data_hourly) > 0)
    
    # Ensure BinStartTime is POSIXct
    req(lubridate::is.POSIXct(data_hourly$BinStartTime))
    
    # Convert to long format for ggplot faceting
    data_long <- tryCatch(melt(data_hourly, 
                               id.vars = "BinStartTime", 
                               measure.vars = patterns("^Count_"), 
                               variable.name = "Label", value.name = "Count"),
                          error = function(e) NULL)
    req(data_long)
    
    data_long[, Label := gsub("Count_", "", Label)]
    
    ggplot(data_long, aes(x = BinStartTime, y = Count)) +
      geom_col(fill = "lightblue") + 
      facet_wrap(~ Label, scales = "free_y", ncol = 2) + 
      labs(title = "Total Hourly Beambreak Counts per Channel",
           x = "Time", y = "Total Count") +
      theme_bw(base_size = 10) +
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            strip.text = element_text(size = 8)) +
      scale_x_datetime(date_breaks = "3 hours", date_labels = "%H:%M") # Adjust breaks as needed
  })
  
  # == Table Tabs ==
  # Minute Bin Table (File 6)
  output$tbl_minute <- DT::renderDataTable({
    data <- loaded_file6()
    req(nrow(data) > 0)
    # Ensure BinStartTime is formatted nicely if needed (or keep POSIXct)
    # data[, BinStartTime := format(BinStartTime, "%Y-%m-%d %H:%M:%S")]
    datatable(data, options = list(pageLength = 15, scrollX = TRUE), rownames = FALSE)
  })
  
  # Raw States Table (File 3)
  output$tbl_raw_states <- DT::renderDataTable({
    data <- loaded_file3()
    req(nrow(data) > 0)
    # Select relevant columns - Timestamp, maybe Raw Pin, and Channel states
    cols_to_show <- intersect(c("Timestamp", "DigitalPins_Raw", paste0("Channel_", 0:7)), names(data))
    datatable(data[, ..cols_to_show], options = list(pageLength = 15, scrollX = TRUE), rownames = FALSE)
  })
  
  # Wheel Movement Table
  output$tbl_wheel <- DT::renderDataTable({
    data <- loaded_wheel()
    req(nrow(data) > 0)
    datatable(data, options = list(pageLength = 15, scrollX = TRUE), rownames = FALSE)
  })
  
  # Actigraphy Table (Placeholder)
  # output$tbl_actigraphy <- DT::renderDataTable({...})
  
  
  # --- Download Handlers ---
  output$download_minute <- downloadHandler(
    filename = function() { paste0("minute_binned_data_", input$experiment, "_", input$cohort, "_", input$rat, "_", Sys.Date(), ".csv") },
    content = function(file) { write.csv(loaded_file6(), file, row.names = FALSE) }
  )
  
  output$download_file3 <- downloadHandler(
    filename = function() { paste0("raw_states_file3_", input$experiment, "_", input$cohort, "_", input$rat, "_", Sys.Date(), ".csv") },
    content = function(file) { write.csv(loaded_file3(), file, row.names = FALSE) }
  )
  
  output$download_wheel <- downloadHandler(
    filename = function() { paste0("wheel_movement_", input$experiment, "_", input<span class="math-inline">experiment, "\_", input</span>cohort, "_", input$rat, "_", Sys.Date(), ".csv") },
    content = function(file) { write.csv(loaded_wheel(), file, row.names = FALSE) }
  )
  
  # output$download_actigraphy <- downloadHandler(...)
  
} # End Server Function

# --- Run the Shiny App ---
shinyApp(ui = ui, server = server)