# ============================================================================
# Script: appV3.R 
# Author: Simeone Marino, Noah Muscat
# Date: 2025-04-06
# Description:
#   Optimized R Shiny app for visualizing pre-processed RBB data.
#   Uses a pre-generated manifest file ('processed_manifest.rds') for fast
#   file discovery. Uses caching (shiny::bindCache) and efficient data
#   loading (data.table). Reads processed files and displays:
#   - Daily Beambreak Count Plots (from File 8) - Daily X-axis labels
#   - Hourly Beambreak Count Plots (from File 7) - Daily X-axis labels
#   - Circadian Analysis Plot (Aggregated hourly counts from File 7)
#   - Hourly Bin Data Table (from File 7)
#   - Daily Bin Data Table (from File 8)
#   - Labeled Events Table (from File 5)
#   - Daily Wheel Movement Plot (from WheelMovement files)
#   Formats datetime columns for tables within R server logic using base::format.
#
# Data Source: Reads 'processed_manifest.rds' and associated data files from
#              the processed_data_dir. Manifest file must be generated by
#              the 'RBB_LocalAnalysis.R' script and include entries for
#              File 5, File 7, File 8, and WheelMovement.
# Dependencies: shiny (>= 1.6.0), DT, data.table, dplyr, tidyr, scales,
#               lubridate, stringr, ggplot2, shinycssloaders, bit64
# ============================================================================

# --- Load Required Libraries ---
suppressPackageStartupMessages({
  library(shiny)
  library(DT)
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(lubridate)
  library(stringr)
  library(ggplot2)
  library(shinycssloaders)
  library(bit64)
  library(scales) # Added for date/time scale formatting helpers
})

# --- Global Parameters ---
processed_data_dir <- "/nfs/turbo/umms-brendonw/RBB_Data_Cleaned"
manifest_file_path <- file.path(
  processed_data_dir,
  "processed_manifest.rds"
)

# Must match processing script
CHANNEL_LABELS <- c(
  "Water_1_Beambreak", "Water_2_Beambreak", "Food_1_Beambreak",
  "Food_2_Beambreak", "Water_1_Dispense", "Water_2_Dispense",
  "Food_1_Dispense", "Food_2_Dispense"
)
COUNT_COL_NAMES <- paste("Count", CHANNEL_LABELS, sep = "_")
DURATION_COL_NAMES <- paste("TotalDuration", CHANNEL_LABELS, sep = "_")

# --- UI Definition ---
ui <- fluidPage(
  tags$head(
    tags$style(HTML("
      .shiny-input-container,
      .shiny-input-container > label {
        font-size: 14px !important;
        font-family: Arial, sans-serif !important;
      }
      .shiny-spinner-output-container { min-height: 300px; }
    "))
  ),
  titlePanel(
    "RBB Experiment Portal"
  ),
  
  sidebarLayout(
    sidebarPanel(
      width = 3,
      selectInput(
        "experiment",
        "Experiment",
        choices = c("Loading..." = "")
      ),
      selectInput(
        "cohort",
        "Cohort",
        choices = c("Loading..." = "")
      ),
      uiOutput("rat_select_ui"),
      radioButtons(
        "date_choice",
        "Select Date Option:",
        choices = c("All Available Dates" = "all",
                    "Single Date" = "single",
                    "Date Range" = "range"),
        selected = "all"
      ),
      uiOutput("date_input_ui"),
      actionButton(
        "refresh_manifest",
        "Refresh File List",
        icon = icon("refresh"),
        style = "font-size:80%"
      )
    ), # end sidebarPanel
    
    mainPanel(
      width = 9,
      tabsetPanel(
        id = "main_tabs",
        type = "tabs",
        # --- New Tab Order ---
        tabPanel( # Moved Daily Plot first
          "Daily Plots (Counts)",
          withSpinner(
            plotOutput("daily_plots_output", height = "600px")
          )
        ),
        tabPanel( # Moved Hourly Plot second
          "Hourly Plots (Counts)",
          withSpinner(
            plotOutput("plot_hourly_counts", height = "600px")
          )
        ),
        tabPanel( # Added Circadian Plot
          "Circadian Analysis",
          withSpinner(
            plotOutput("plot_circadian", height="600px")
          )
        ),
        tabPanel( # Hourly Table
          "Hourly Bin Data (File 7)",
          withSpinner(DT::dataTableOutput('tbl_hourly')),
          downloadButton('download_hourly', 'Download Hourly Data')
        ),
        tabPanel( # Daily Table
          "Daily Bin Data (File 8)",
          withSpinner(DT::dataTableOutput('tbl_daily')),
          downloadButton('download_daily', 'Download Daily Data')
        ),
        tabPanel( # Events Table
          "Labeled Events (File 5)",
          withSpinner(DT::dataTableOutput('tbl_file5')),
          downloadButton('download_file5', 'Download Labeled Events')
        ),
        tabPanel( # Wheel Plot
          "Daily Wheel Movement",
          withSpinner(
            plotOutput('plot_wheel_daily', height = "600px")
          )
        ),
        tabPanel(
          "IN PROGRESS - Actigraphy",
          p("Actigraphy analysis module pending.")
        )
        # --- End New Tab Order ---
      ) # end tabsetPanel
    ) # end mainPanel
  ), # end sidebarLayout
  
  div("RBB App Version: V.3.9", align = "center") 
  
) # end fluidPage

# --- Server Logic ---
server <- function(input, output, session) {
  
  # --- File Discovery from Manifest ---
  manifest_trigger <- reactiveVal(0)
  observeEvent(input$refresh_manifest, {
    manifest_trigger(manifest_trigger() + 1)
  })
  
  all_processed_files_info <- reactive({
    # Depend on trigger
    manifest_trigger()
    message("--- all_processed_files_info: Reading manifest (or cache miss) ---")
    
    # Check existence
    req(file.exists(manifest_file_path), cancelOutput = FALSE)
    validate(
      need(
        file.exists(manifest_file_path),
        paste("ERROR: Manifest file not found at:", manifest_file_path,
              "\nPlease ensure the processing script has run successfully.")
      )
    )
    
    # Read manifest
    manifest_data <- tryCatch({
      readRDS(manifest_file_path)
    }, error = function(e) {
      showNotification(
        paste("Error reading manifest file:", manifest_file_path,
              "Error:", e$message),
        type = "error",
        duration = 15
      )
      NULL # Return NULL on error
    })
    
    # Basic Validation
    req(!is.null(manifest_data), cancelOutput = FALSE)
    validate(
      need(
        is.data.frame(manifest_data) || is.data.table(manifest_data),
        "Manifest file did not contain a data frame."
      )
    )
    required_cols <- c("file_path", "experiment_id", "cohort_id",
                       "rat_id", "date", "file_type")
    validate(
      need(
        all(required_cols %in% names(manifest_data)),
        paste("Manifest file is missing required columns (e.g.,",
              paste(required_cols, collapse = ", "), ").")
      )
    )
    
    # Ensure data.table
    if (!is.data.table(manifest_data)) {
      manifest_data <- as.data.table(manifest_data)
    }
    
    # Ensure date column is Date type
    if (nrow(manifest_data) > 0 && !"Date" %in% class(manifest_data$date)) {
      message("Converting 'date' column in manifest to Date type.")
      manifest_data[, date := lubridate::as_date(date)]
      if (anyNA(manifest_data$date)) {
        warning("NAs introduced during manifest 'date' column conversion.")
      }
    }
    
    # Remove rows with missing essential info
    if (nrow(manifest_data) > 0) {
      original_rows <- nrow(manifest_data)
      manifest_data <- na.omit(manifest_data, cols = required_cols)
      rows_removed <- original_rows - nrow(manifest_data)
      if (rows_removed > 0) {
        warning(
          paste("Removed", rows_removed,
                "rows from manifest due to missing essential info.")
        )
      }
    }
    
    # Log result and return
    if (nrow(manifest_data) == 0) {
      showNotification(
        paste("Manifest file read successfully,",
              "but contains no valid entries after cleaning."),
        type = "warning",
        duration = 15
      )
    } else {
      message(
        paste("Read", nrow(manifest_data), "valid entries from manifest file.")
      )
    }
    message("--- all_processed_files_info: END ---")
    
    # Return even if empty, downstream req handles it
    return(manifest_data)
    
  }) %>%
    # Cache based on trigger, manifest path, mod time, and process number
    bindCache(
      manifest_trigger(),
      manifest_file_path,
      file.info(manifest_file_path)$mtime,
      Sys.getenv("R_SHINY_PROCESS_NUMBER")
    )
  
  
  # --- Populate UI Selectors ---
  observe({
    info <- req(all_processed_files_info())
    req(nrow(info) > 0) # Don't proceed if manifest was empty
    
    choices <- sort(unique(isolate(info$experiment_id)))
    current_selection <- isolate(input$experiment)
    
    # Select first item, or keep current if it's still valid
    selected_choice <- if (!is.null(current_selection) &&
                           current_selection %in% choices) {
      current_selection
    } else {
      first(choices)
    }
    
    updateSelectInput(
      session,
      "experiment",
      choices = choices,
      selected = selected_choice
    )
  })
  
  observe({
    req(input$experiment)
    info <- req(all_processed_files_info())
    req(nrow(info) > 0)
    
    choices <- sort(unique(
      isolate(info[experiment_id == input$experiment, ]$cohort_id)
    ))
    current_selection <- isolate(input$cohort)
    
    selected_choice <- if (!is.null(current_selection) &&
                           current_selection %in% choices) {
      current_selection
    } else {
      first(choices)
    }
    
    updateSelectInput(
      session,
      "cohort",
      choices = choices,
      selected = selected_choice
    )
  })
  
  output$rat_select_ui <- renderUI({
    info <- req(all_processed_files_info())
    req(input$experiment, input$cohort)
    req(nrow(info) > 0)
    
    choices <- sort(unique(
      isolate(
        info[experiment_id == input$experiment &
               cohort_id == input$cohort, ]$rat_id
      )
    ))
    current_selection <- isolate(input$rat)
    
    selected_choice <- if (!is.null(current_selection) &&
                           current_selection %in% choices) {
      current_selection
    } else {
      first(choices)
    }
    
    selectInput(
      "rat",
      label = "Rat ID",
      choices = choices,
      selected = selected_choice
    )
  })
  
  available_dates <- reactive({
    info <- req(all_processed_files_info())
    # Ensure inputs are valid before filtering
    req(input$experiment, input$experiment != "")
    req(input$cohort, input$cohort != "")
    req(input$rat, input$rat != "")
    req(nrow(info) > 0)
    
    info_sub <- isolate(
      info[experiment_id == input$experiment &
             cohort_id == input$cohort &
             rat_id == input$rat & !is.na(date), ]
    )
    sort(unique(info_sub$date))
  })
  
  output$date_input_ui <- renderUI({
    dates <- available_dates()
    validate(
      need(length(dates) > 0, "No dates found for this selection.")
    )
    
    current_single <- isolate(input$single_date)
    current_range <- isolate(input$date_range)
    
    if (input$date_choice == "single") {
      selected_date_val <- format(last(dates), "%Y-%m-%d") # Default last
      if (!is.null(current_single) &&
          (ymd(current_single, quiet = TRUE) %in% dates)) {
        selected_date_val <- current_single
      }
      selectInput(
        "single_date",
        "Select Date",
        choices = format(dates, "%Y-%m-%d"),
        selected = selected_date_val
      )
    } else if (input$date_choice == "range") {
      start_date_val <- first(dates)
      end_date_val <- last(dates)
      if (!is.null(current_range) && length(current_range) == 2) {
        if (current_range[1] %in% dates) start_date_val <- current_range[1]
        if (current_range[2] %in% dates) end_date_val <- current_range[2]
        if (start_date_val > end_date_val) start_date_val <- first(dates) # Reset if invalid
      }
      dateRangeInput(
        "date_range",
        label = "Select Date Range",
        start = start_date_val,
        end = end_date_val,
        min = first(dates),
        max = last(dates)
      )
    } else { # 'all' dates selected
      NULL
    }
  })
  
  
  # --- Data Loading Reactives ---
  selected_files_base <- reactive({
    info <- req(all_processed_files_info())
    # Validate inputs
    req(input$experiment, input$experiment != "")
    req(input$cohort, input$cohort != "")
    req(input$rat, input$rat != "")
    req(input$date_choice)
    req(nrow(info) > 0)
    
    # Filter by exp, cohort, rat
    filtered_info <- info[experiment_id == input$experiment &
                            cohort_id == input$cohort &
                            rat_id == input$rat, ]
    req(nrow(filtered_info) > 0, cancelOutput = FALSE,
        message = "No manifest entries match Experiment/Cohort/Rat selection.")
    
    # Filter by Date (only if not 'all')
    if (input$date_choice == "single") {
      req(input$single_date)
      selected_date <- ymd(input$single_date, quiet = TRUE)
      req(!is.na(selected_date))
      filtered_info <- filtered_info[date == selected_date, ]
    } else if (input$date_choice == "range") {
      req(input$date_range)
      start_date <- ymd(input$date_range[1], quiet = TRUE)
      end_date <- ymd(input$date_range[2], quiet = TRUE)
      req(!is.na(start_date), !is.na(end_date))
      filtered_info <- filtered_info[date >= start_date & date <= end_date, ]
    }
    
    if (nrow(filtered_info) == 0) {
      showNotification(
        "No processed files found for the selected criteria (including date).",
        type = "warning"
      )
    }
    req(nrow(filtered_info) > 0, cancelOutput = FALSE) # Need files to proceed
    return(filtered_info)
  })
  
  # Helper function to read selected files
  load_selected_files <- function(file_type_short) {
    base_info <- selected_files_base()
    req(nrow(base_info) > 0) # Need base info for selection
    
    files_to_load_info <- base_info[file_type == file_type_short, ]
    # Need entries for the specific file type for this selection
    req(nrow(files_to_load_info) > 0, cancelOutput = FALSE)
    
    files_to_load <- files_to_load_info$file_path
    
    # Check existence on disk
    files_exist <- file.exists(files_to_load)
    if (!any(files_exist)) {
      showNotification(
        paste("Manifest lists", length(files_to_load), file_type_short,
              "file(s), but none exist on disk for this selection."),
        type = "error"
      )
      return(data.table()) # Return empty table
    }
    # Load only the files that actually exist
    if (!all(files_exist)) {
      warning(
        paste("Manifest lists", length(files_to_load), file_type_short,
              "files, but only", sum(files_exist), "found on disk.")
      )
      files_to_load <- files_to_load[files_exist]
    }
    
    message(
      paste(">>> Reading", length(files_to_load), " '", file_type_short,
            "' file(s) from disk (or cache miss)... paths from manifest.")
    )
    
    tryCatch({
      # Read each file and immediately coerce time column before rbindlist
      data_list <- lapply(files_to_load, function(f) {
        dt <- data.table::fread(f)
        if (nrow(dt) == 0) { # Handle empty files read by fread
          return(dt)
        }
        
        # Identify expected time column
        time_col_name <- NULL
        if (file_type_short %in% c("File6", "File7", "File8")) {
          time_col_name <- "BinStartTime"
        } else if (file_type_short == "File5") {
          time_col_name <- "StartTime"
        } else if (file_type_short == "WheelMovement") {
          time_col_name <- "Timestamp"
        }
        
        # If a time column is expected and exists, ensure it's POSIXct
        if (!is.null(time_col_name) && time_col_name %in% names(dt)) {
          t_col <- time_col_name
          if (!lubridate::is.POSIXct(dt[[t_col]])) {
            message(paste("Coercing", t_col, "to POSIXct in file:", basename(f)))
            original_values <- dt[[t_col]]
            converted_time <- lubridate::parse_date_time(
              original_values,
              orders = c("Ymd HMS", "Ymd HM", "Ymd"),
              tz = "UTC", quiet = TRUE
            )
            dt[, (t_col) := converted_time]
            
            # Check conversion results
            if (all(is.na(dt[[t_col]])) && !all(is.na(original_values))) {
              warning("All time values failed parsing in file: ", basename(f))
              dt[, (t_col) := as.POSIXct(get(t_col), origin="1970-01-01", tz="UTC")]
            } else if (!lubridate::is.POSIXct(dt[[t_col]])) {
              warning("Could not reliably convert ", t_col, " to POSIXct in file: ", basename(f))
              dt[, (t_col) := as.POSIXct(NA_real_, origin="1970-01-01", tz="UTC")]
            }
          }
        } else if (nrow(dt) > 0 && !is.null(time_col_name)) {
          warning(
            paste("Expected time column '", time_col_name,
                  "' not found in non-empty file:", basename(f))
          )
        }
        return(dt)
      }) # End lapply
      
      # Combine list of (potentially type-coerced) tables
      combined_data <- data.table::rbindlist(
        data_list, fill = TRUE, use.names = TRUE
      )
      
      # --- Further Type Conversion (Safety Net) ---
      # Counts
      count_cols <- grep("^Count_", names(combined_data), value = TRUE)
      for (c_col in count_cols) {
        if (!is.integer(combined_data[[c_col]])) {
          combined_data[, (c_col) := as.integer(get(c_col))]
        }
      }
      # Durations
      duration_cols <- grep("^TotalDuration_", names(combined_data), value = TRUE)
      duration_cols <- c(duration_cols,
                         intersect("Duration", names(combined_data)))
      for (d_col in duration_cols) {
        if (!is.numeric(combined_data[[d_col]])) {
          current_vals <- combined_data[[d_col]]
          converted_vals <- suppressWarnings(as.numeric(current_vals))
          if (anyNA(converted_vals) &&
              !all(is.na(current_vals[is.na(converted_vals)]))) {
            warning(paste("NAs produced by coercion converting '", d_col, "'"))
          }
          combined_data[, (d_col) := converted_vals]
        }
      }
      # Wheel Movement
      if ("Wheel_Movement" %in% names(combined_data) &&
          !is.numeric(combined_data$Wheel_Movement)) {
        combined_data[, Wheel_Movement := as.numeric(Wheel_Movement)]
      }
      # --- End Type Conversion ---
      
      # Order by primary time column if present and valid
      time_col_order <- intersect(c("Timestamp", "BinStartTime", "StartTime"),
                                  names(combined_data))
      if (length(time_col_order) > 0 &&
          time_col_order[1] %in% names(combined_data)) {
        # Check for NAs before ordering
        if (anyNA(combined_data[[time_col_order[1]]])) {
          warning(
            paste("NA values found in time column used for ordering ('",
                  time_col_order[1], "'). Ordering might be affected.")
          )
        }
        setorderv(combined_data, time_col_order[1], na.last = TRUE)
      }
      
      message(
        paste("Loaded data dimensions for", file_type_short, ":",
              nrow(combined_data), "rows,", ncol(combined_data), "cols.")
      )
      return(combined_data)
      
    }, error = function(e) {
      showNotification(
        paste("Error in load_selected_files for", file_type_short, ":", e$message),
        type = "error", duration = 15
      )
      return(data.table()) # Return empty table on error
    })
  } # End load_selected_files
  
  
  # Cache key reactive
  cache_key_inputs <- reactive({
    list(input$experiment, input$cohort, input$rat, input$date_choice,
         input$single_date, input$date_range)
  })
  
  # Cached data loading reactives
  loaded_file5 <- reactive({ load_selected_files("File5") }) %>%
    bindCache(cache_key_inputs())
  loaded_file7 <- reactive({ load_selected_files("File7") }) %>%
    bindCache(cache_key_inputs())
  loaded_file8 <- reactive({ load_selected_files("File8") }) %>%
    bindCache(cache_key_inputs())
  loaded_wheel <- reactive({ load_selected_files("WheelMovement") }) %>%
    bindCache(cache_key_inputs())
  
  # --- Render Outputs ---
  
  # == Plotting Tabs ==
  output$daily_plots_output <- renderPlot({
    data_daily <- loaded_file8()
    validate(
      need(nrow(data_daily) > 0,
           "No daily summary data (File 8) available for this selection.")
    )
    # Ensure date type
    if (nrow(data_daily) > 0 && !inherits(data_daily$BinStartTime, "Date")) {
      data_daily[, BinStartTime := as.Date(BinStartTime)]
    }
    validate(
      need(inherits(data_daily$BinStartTime, "Date"),
           "BinStartTime in File 8 could not be converted to Date.")
    )
    # Reshape data
    plot_cols <- intersect(COUNT_COL_NAMES, names(data_daily))
    validate(
      need(length(plot_cols) > 0,
           "No 'Count_*' columns found in File 8 data.")
    )
    data_long <- tryCatch(
      melt(data_daily, id.vars = "BinStartTime", measure.vars = plot_cols,
           variable.name = "Label", value.name = "Count", na.rm = TRUE),
      error = function(e) NULL
    )
    validate(
      need(!is.null(data_long) && nrow(data_long) > 0,
           "Failed to reshape File 8 data for plotting.")
    )
    data_long[, Label := gsub("Count_", "", Label)]
    
    # Generate plot
    ggplot(data_long, aes(x = BinStartTime, y = Count)) +
      geom_col(fill = "steelblue") +
      facet_wrap(~ Label, scales = "free_y", ncol = 4) +
      labs(
        title = "Total Daily Beambreak Counts per Channel",
        x = "Date",
        y = "Total Count"
      ) +
      theme_bw(base_size = 10) +
      theme(
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 7),
        strip.text = element_text(size = 8)
      ) +
      scale_x_date(
        date_breaks = "1 day",
        date_labels = "%m/%d"
      )
  }, height = 600)
  
  output$plot_hourly_counts <- renderPlot({
    data_hourly <- loaded_file7()
    validate(
      need(nrow(data_hourly) > 0,
           "No hourly summary data (File 7) available for this selection.")
    )
    # Ensure BinStartTime is POSIXct
    if (nrow(data_hourly) > 0 && !inherits(data_hourly$BinStartTime, "POSIXct")) {
      data_hourly[, BinStartTime := as.POSIXct(
        BinStartTime, origin="1970-01-01", tz="UTC"
      )]
    }
    validate(
      need(inherits(data_hourly$BinStartTime, "POSIXct"),
           "BinStartTime in File 7 could not be converted to POSIXct.")
    )
    
    # Reshape data
    plot_cols <- intersect(COUNT_COL_NAMES, names(data_hourly))
    validate(
      need(length(plot_cols) > 0,
           "No 'Count_*' columns found in File 7 data.")
    )
    data_long <- tryCatch(
      melt(data_hourly, id.vars = "BinStartTime", measure.vars = plot_cols,
           variable.name = "Label", value.name = "Count", na.rm = TRUE),
      error = function(e) {
        warning("Error melting File 7 data: ", e$message)
        NULL
      }
    )
    validate(
      need(!is.null(data_long) && nrow(data_long) > 0,
           "Failed to reshape File 7 data for plotting or no count data.")
    )
    data_long[, Label := gsub("Count_", "", Label)]
    
    # Generate plot
    ggplot(data_long, aes(x = BinStartTime, y = Count)) +
      geom_col(fill = "lightblue") +
      facet_wrap(~ Label, scales = "free_y", ncol = 4) +
      labs(
        title = "Total Hourly Beambreak Counts per Channel",
        x = "Time (Grouped by Day)", # Use daily breaks/labels
        y = "Total Count"
      ) +
      theme_bw(base_size = 10) +
      theme(
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 7),
        strip.text = element_text(size = 8)
      ) +
      # Use daily breaks and labels for x-axis
      scale_x_datetime(
        date_breaks = "1 day",
        date_labels = "%m/%d"
      )
  }, height = 600)
  
  output$plot_circadian <- renderPlot({
    data_hourly <- loaded_file7()
    validate(
      need(nrow(data_hourly) > 0,
           "No hourly summary data (File 7) available for circadian analysis.")
    )
    # Ensure BinStartTime is POSIXct
    if (nrow(data_hourly) > 0 && !inherits(data_hourly$BinStartTime, "POSIXct")) {
      data_hourly[, BinStartTime := as.POSIXct(
        BinStartTime, origin="1970-01-01", tz="UTC"
      )]
    }
    validate(
      need(inherits(data_hourly$BinStartTime, "POSIXct"),
           "BinStartTime in File 7 could not be converted to POSIXct.")
    )
    
    # Reshape data
    plot_cols <- intersect(COUNT_COL_NAMES, names(data_hourly))
    validate(
      need(length(plot_cols) > 0,
           "No 'Count_*' columns found in File 7 data.")
    )
    data_long <- tryCatch(
      melt(data_hourly, id.vars = "BinStartTime", measure.vars = plot_cols,
           variable.name = "Label", value.name = "Count", na.rm = TRUE),
      error = function(e) {
        warning("Error melting File 7 data for circadian: ", e$message)
        NULL
      }
    )
    validate(
      need(!is.null(data_long) && nrow(data_long) > 0,
           "Failed to reshape File 7 data or no count data for circadian.")
    )
    data_long[, Label := gsub("Count_", "", Label)]
    
    # Add HourOfDay column (UTC)
    data_long[, HourOfDay := lubridate::hour(BinStartTime)]
    
    # Aggregate total counts by HourOfDay and Label
    circadian_data <- data_long[,
                                .(TotalCount = sum(Count, na.rm = TRUE)),
                                by = .(HourOfDay, Label)
    ]
    validate(
      need(nrow(circadian_data) > 0, "No data after circadian aggregation.")
    )
    
    # Generate plot
    ggplot(circadian_data, aes(x = HourOfDay, y = TotalCount)) +
      geom_col(fill = "seagreen") +
      facet_wrap(~ Label, scales = "free_y", ncol = 4) +
      labs(
        title = "Circadian Pattern (Total Counts per Hour of Day)",
        subtitle = "Aggregated across selected date range (UTC)",
        x = "Hour of Day (UTC)",
        y = "Total Count"
      ) +
      theme_bw(base_size = 10) +
      theme(
        axis.text.x = element_text(size = 8),
        strip.text = element_text(size = 8)
      ) +
      # Set X-axis breaks to show hours
      scale_x_continuous(breaks = seq(0, 23, by = 2))
    
  }, height = 600)
  
  
  output$plot_wheel_daily <- renderPlot({
    data_wheel_raw <- loaded_wheel(); validate(need(nrow(data_wheel_raw) > 0, "...")); validate(need(all(c("Timestamp", "Wheel_Movement") %in% names(data_wheel_raw)), "..."), need(inherits(data_wheel_raw$Timestamp, "POSIXct"), "..."), need(is.numeric(data_wheel_raw$Wheel_Movement), "..."))
    data_wheel_daily <- data_wheel_raw[, .(Daily_Wheel_Movement = sum(Wheel_Movement, na.rm = TRUE)), by = .(Date = as.Date(Timestamp))]; validate(need(nrow(data_wheel_daily) > 0, "..."))
    date_range_days <- as.numeric(diff(range(data_wheel_daily$Date, na.rm = TRUE))); date_break_setting <- if (is.na(date_range_days) || date_range_days <= 7) {"1 day"} else if (date_range_days <= 60) {"1 week"} else if (date_range_days <= 365) {"1 month"} else {"3 months"}; date_label_format <- if (date_range_days <= 90) {"%m-%d"} else {"%Y-%m"}
    ggplot(data_wheel_daily, aes(x = Date, y = Daily_Wheel_Movement)) + geom_col(fill = "darkorange") + labs(title = "Total Daily Wheel Movement", x = "Date", y = "Total Movement (Sum of diffs)") + theme_bw(base_size = 10) + theme( axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 8) ) + scale_x_date( date_breaks = date_break_setting, date_labels = date_label_format ) + scale_y_continuous(labels = scales::label_number(accuracy = 0.1))
  }, height = 600)
  
  
  # == Table Tabs ==
  
  output$tbl_hourly <- DT::renderDataTable({
    data <- loaded_file7(); validate(need(nrow(data) > 0, "...")); if (!"POSIXct" %in% class(data$BinStartTime)) { data[, BinStartTime := as.POSIXct( BinStartTime, origin = "1970-01-01", tz = "UTC" )] }; validate( need(inherits(data$BinStartTime,"POSIXct"),"...") )
    data_display <- copy(data); data_display[, BinStartTime_Formatted := format( BinStartTime, format = '%Y-%m-%d %H:%M:%S', tz = 'UTC' )]
    data_for_dt <- data_display[, !"BinStartTime"]; setnames(data_for_dt, "BinStartTime_Formatted", "BinStartTime"); if ("BinStartTime" %in% names(data_for_dt)) { setcolorder(data_for_dt, neworder = "BinStartTime") }
    datatable( data_for_dt, options = list( pageLength = 15, scrollX = TRUE, searchDelay = 500 ), rownames = FALSE, filter = 'top' )
  }, server = TRUE)
  
  output$tbl_daily <- DT::renderDataTable({
    data <- loaded_file8(); validate(need(nrow(data) > 0, "...")); if (nrow(data) > 0 && !inherits(data$BinStartTime, "Date")) { data[, BinStartTime := as.Date(BinStartTime)] }; validate(need(inherits(data$BinStartTime,"Date"), "..."))
    data_display <- copy(data); if ("BinStartTime" %in% names(data_display)) { setcolorder(data_display, neworder = "BinStartTime") }
    datatable( data_display, options = list( pageLength = 15, scrollX = TRUE, searchDelay = 500 ), rownames = FALSE, filter = 'top' )
  })
  
  output$tbl_file5 <- DT::renderDataTable({
    data <- loaded_file5(); validate(need(nrow(data) > 0, "...")); validate(need(all(c("StartTime", "Label", "Duration") %in% names(data)),"...")); if (!"POSIXct" %in% class(data$StartTime)) { data[, StartTime := as.POSIXct( StartTime, origin = "1970-01-01", tz = "UTC" )] }; validate(need(inherits(data$StartTime,"POSIXct"), "..."))
    data_display <- copy(data)[, Duration := round(Duration, 3)]; data_display[, StartTime_Formatted := format( StartTime, format = '%Y-%m-%d %H:%M:%S', tz = 'UTC' )]
    datatable( data_display[, .(StartTime = StartTime_Formatted, Label, Duration)], options = list( pageLength = 15, scrollX = TRUE, searchDelay = 500 ), rownames = FALSE, filter = 'top' )
  }, server = TRUE)
  
  
  # --- Download Handlers ---
  
  output$download_hourly <- downloadHandler(
    filename = function() { paste0("hourly_binned_data_", input$experiment, "_", input$cohort, "_", input$rat, "_", Sys.Date(), ".csv") }, content = function(file) { data_to_save <- loaded_file7(); data.table::fwrite(data_to_save, file) }
  )
  
  output$download_daily <- downloadHandler(
    filename = function() { paste0("daily_binned_data_", input$experiment, "_", input$cohort, "_", input$rat, "_", Sys.Date(), ".csv") }, content = function(file) { data_to_save <- loaded_file8(); data.table::fwrite(data_to_save, file) }
  )
  
  output$download_file5 <- downloadHandler(
    filename = function() { paste0("labeled_events_file5_", input$experiment, "_", input$cohort, "_", input$rat, "_", Sys.Date(), ".csv") }, content = function(file) { data_to_save <- loaded_file5(); data.table::fwrite(data_to_save, file) }
  )
  
} # End Server Function

# --- Run the Shiny App ---
shinyApp(ui = ui, server = server)