# ============================================================================
# Script: appV3.R
# Author: Noah Muscat, Simeone Marino
# Date: 2025-04-05 # Updated Date
# Description:
#   Optimized R Shiny app for visualizing pre-processed RBB data.
#   Uses a pre-generated manifest file ('processed_manifest.rds') for fast
#   file discovery. Uses caching (shiny::bindCache) and efficient data
#   loading (data.table) to improve performance. Reads processed files
#   (Files 3, 6, 7, 8, WheelMovement) and displays tables and plots.
#
# Data Source: Reads 'processed_manifest.rds' and associated data files from
#              the processed_data_dir specified below. Manifest file must be
#              generated by the 'RBB_Data_Processor_Final_CLI.R' script.
# Dependencies: shiny (>= 1.6.0 recommended for bindCache), DT, data.table,
#               dplyr, tidyr, lubridate, stringr, ggplot2, shinycssloaders, bit64
# ============================================================================

# --- Load Required Libraries ---
# Load packages quietly for deployed app
suppressPackageStartupMessages({
  library(shiny)
  library(DT)
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(lubridate)
  library(stringr)
  library(ggplot2)
  library(shinycssloaders)
  library(bit64) # May help with dependency installation on some systems
})

# --- Global Parameters ---

# Path to the *main* directory where the PROCESSING SCRIPT saved its output files
# ** Use absolute path **
processed_data_dir <- "/nfs/turbo/umms-brendonw/RBB_Data_Cleaned" # <<< ENSURE THIS MATCHES PROCESSING SCRIPT OUTPUT

# <<< ADDED: Path to the manifest file generated by the processing script >>>
manifest_file_path <- file.path(processed_data_dir, "processed_manifest.rds")

# Fixed descriptive labels for the 8 digital channels (0-7) - MUST MATCH PROCESSING SCRIPT
CHANNEL_LABELS <- c(
  "Water_1_Beambreak",  # Channel 0
  "Water_2_Beambreak",  # Channel 1
  "Food_1_Beambreak",   # Channel 2
  "Food_2_Beambreak",   # Channel 3
  "Water_1_Dispense",   # Channel 4
  "Water_2_Dispense",   # Channel 5
  "Food_1_Dispense",    # Channel 6
  "Food_2_Dispense"     # Channel 7
)

# Expected column names for binned data (using Measure_Label format)
COUNT_COL_NAMES <- paste("Count", CHANNEL_LABELS, sep = "_")
DURATION_COL_NAMES <- paste("TotalDuration", CHANNEL_LABELS, sep = "_") # Define for potential future use

# --- UI Definition ---
ui <- fluidPage(
  tags$head(
    tags$style(HTML("
      .shiny-input-container, .shiny-input-container > label { font-size: 14px !important; font-family: Arial, sans-serif !important; }
      .shiny-spinner-output-container { min-height: 300px; }
    "))
  ),
  titlePanel("RBB Experiment Portal (Processed Data Viewer - Manifest Version)"), # Updated title slightly
  
  sidebarLayout(
    sidebarPanel(
      width = 3,
      selectInput("experiment", "Experiment", choices = c("Loading..." = "")),
      selectInput("cohort", "Cohort", choices = c("Loading..." = "")),
      uiOutput("rat_select_ui"),
      radioButtons("date_choice", "Select Date Option:",
                   choices = c("All Available Dates" = "all", "Single Date" = "single", "Date Range" = "range"),
                   selected = "all"),
      uiOutput("date_input_ui"),
      # Added action button to manually refresh manifest read if needed (optional)
      actionButton("refresh_manifest", "Refresh File List", icon = icon("refresh"), style = "font-size:80%")
    ),
    mainPanel(
      width = 9,
      tabsetPanel(
        id = "main_tabs", # Add an ID for potential future use
        type = "tabs",
        tabPanel("Daily Plots (Counts)", withSpinner(plotOutput("daily_plots_output", height = "600px"))), # Set height directly
        tabPanel("Minute Bin Data (File 6)",
                 withSpinner(DT::dataTableOutput('tbl_minute')),
                 downloadButton('download_minute', 'Download Minute Data')
        ),
        tabPanel("Raw States (File 3)",
                 withSpinner(DT::dataTableOutput('tbl_raw_states')),
                 downloadButton('download_file3', 'Download Raw States Data')
        ),
        tabPanel("Wheel Movement",
                 withSpinner(DT::dataTableOutput('tbl_wheel')),
                 downloadButton('download_wheel', 'Download Wheel Data')
        ),
        tabPanel("IN PROGRESS - Actigraphy", p("Actigraphy analysis module pending."))
      )
    )
  ),
  div("RBB App Version: V.3.2-Manifest", align = "center") # Updated version
)

# --- Server Logic ---
server <- function(input, output, session) {
  
  # --- File Discovery from Manifest ---
  # <<< MODIFIED: Read manifest file instead of scanning directories >>>
  # Reactive value to trigger reload when button is pressed
  manifest_trigger <- reactiveVal(0)
  
  observeEvent(input$refresh_manifest, {
    manifest_trigger(manifest_trigger() + 1)
  })
  
  
  all_processed_files_info <- reactive({
    # Depend on the trigger button
    manifest_trigger()
    
    message("--- all_processed_files_info: Reading manifest (or cache miss) ---")
    
    # Check if manifest file exists before attempting to read
    req(file.exists(manifest_file_path),
        cancelOutput = FALSE) # cancelOutput=FALSE shows notification below if file missing
    
    validate(
      need(file.exists(manifest_file_path),
           paste("ERROR: Manifest file not found at:", manifest_file_path,
                 "\nPlease ensure the processing script has run successfully."))
    )
    
    # Invalidate reactive if the file modification time changes (handled by bindCache below)
    
    manifest_data <- tryCatch({
      readRDS(manifest_file_path)
    }, error = function(e) {
      showNotification(paste("Error reading manifest file:", manifest_file_path, "Error:", e$message), type="error", duration=15)
      NULL # Return NULL on error
    })
    
    # Basic Validation
    req(!is.null(manifest_data), cancelOutput = FALSE) # Require data to be non-NULL
    
    validate(
      need(is.data.frame(manifest_data) || is.data.table(manifest_data), "Manifest file did not contain a data frame."),
      # Check for essential columns needed downstream
      need(all(c("file_path", "experiment_id", "cohort_id", "rat_id", "date", "file_type") %in% names(manifest_data)),
           "Manifest file is missing required columns (e.g., file_path, experiment_id, cohort_id, rat_id, date, file_type).")
    )
    
    # Ensure it's a data.table for consistency downstream
    if (!is.data.table(manifest_data)) {
      manifest_data <- as.data.table(manifest_data)
    }
    
    # Ensure date column is Date type (saveRDS should preserve it, but good practice to check)
    if (nrow(manifest_data) > 0 && !"Date" %in% class(manifest_data$date)) {
      message("Converting 'date' column in manifest to Date type.")
      manifest_data[, date := lubridate::as_date(date)]
      # Check for NAs introduced by conversion
      if(anyNA(manifest_data$date)){
        warning("NAs introduced during manifest 'date' column conversion. Check source data.")
        # Optionally remove rows with NA dates if they cause issues downstream
        # manifest_data <- manifest_data[!is.na(date),]
      }
    }
    
    # Remove rows where essential info might be NA (should have been handled by processor, but defensive check)
    if(nrow(manifest_data) > 0){
      original_rows <- nrow(manifest_data)
      manifest_data <- na.omit(manifest_data, cols=c("file_path", "experiment_id", "cohort_id", "rat_id", "date", "file_type"))
      if(nrow(manifest_data) < original_rows){
        warning("Removed ", original_rows - nrow(manifest_data), " rows from manifest due to missing essential info.")
      }
    }
    
    
    if(nrow(manifest_data) == 0) {
      showNotification("Manifest file read successfully, but contains no valid entries after cleaning.", type = "warning", duration=15)
    } else {
      message("Read ", nrow(manifest_data), " valid entries from manifest file.")
    }
    
    message("--- all_processed_files_info: END ---")
    req(nrow(manifest_data) > 0,
        cancelOutput = FALSE) # Require some data to proceed in downstream reactives, but don't halt completely if empty initially
    
    return(manifest_data)
    
    # <<< MODIFIED: Update bindCache call >>>
    # Cache based on the manifest file path AND its modification time.
    # Include trigger and process number for robustness.
  }) %>% bindCache(manifest_trigger(), manifest_file_path, file.info(manifest_file_path)$mtime, Sys.getenv("R_SHINY_PROCESS_NUMBER"))
  
  
  # --- Populate UI Selectors ---
  # NO CHANGES needed here - they rely on the structure of all_processed_files_info() output,
  # which remains the same (it just comes from the manifest now).
  observe({
    info <- req(all_processed_files_info())
    # Prevent updates if info is empty after validation
    req(nrow(info) > 0)
    choices <- sort(unique(isolate(info$experiment_id)))
    current_selection <- isolate(input$experiment)
    selected_choice <- if (!is.null(current_selection) && current_selection %in% choices) current_selection else first(choices)
    updateSelectInput(session, "experiment", choices = choices, selected=selected_choice)
  })
  
  observe({
    req(input$experiment)
    info <- req(all_processed_files_info())
    req(nrow(info) > 0)
    choices <- sort(unique(isolate(info[experiment_id == input$experiment, ]$cohort_id)))
    current_selection <- isolate(input$cohort)
    selected_choice <- if (!is.null(current_selection) && current_selection %in% choices) current_selection else first(choices)
    updateSelectInput(session, "cohort", choices = choices, selected=selected_choice)
  })
  
  output$rat_select_ui <- renderUI({
    info <- req(all_processed_files_info())
    req(input$experiment, input$cohort)
    req(nrow(info) > 0)
    choices <- sort(unique(isolate(info[experiment_id == input$experiment & cohort_id == input$cohort, ]$rat_id)))
    # Keep existing selection if possible
    current_selection <- isolate(input$rat)
    selected_choice <- if (!is.null(current_selection) && current_selection %in% choices) current_selection else first(choices)
    selectInput("rat", label = "Rat ID", choices = choices, selected = selected_choice)
  })
  
  available_dates <- reactive({
    info <- req(all_processed_files_info())
    # Ensure inputs are non-empty strings before filtering
    req(input$experiment, input$experiment != "")
    req(input$cohort, input$cohort != "")
    req(input$rat, input$rat != "")
    req(nrow(info) > 0)
    info_sub <- isolate(info[experiment_id == input$experiment & cohort_id == input$cohort & rat_id == input$rat & !is.na(date), ])
    sort(unique(info_sub$date))
  })
  
  output$date_input_ui <- renderUI({
    dates <- available_dates()
    # Need to handle case where available_dates might be empty or NULL initially
    validate(need(length(dates) > 0, "No dates found for this selection."))
    
    # Keep existing date selection if possible and valid
    current_single <- isolate(input$single_date)
    current_range <- isolate(input$date_range)
    
    if (input$date_choice == "single") {
      selected_date_val <- format(last(dates), "%Y-%m-%d") # Default to last
      if(!is.null(current_single) && (ymd(current_single, quiet=TRUE) %in% dates)){
        selected_date_val <- current_single
      }
      selectInput("single_date", "Select Date", choices = format(dates, "%Y-%m-%d"), selected = selected_date_val)
    } else if (input$date_choice == "range") {
      start_date_val <- first(dates)
      end_date_val <- last(dates)
      if(!is.null(current_range) && length(current_range) == 2){
        # Check if existing range dates are within the available dates
        if(current_range[1] %in% dates) start_date_val <- current_range[1]
        if(current_range[2] %in% dates) end_date_val <- current_range[2]
        # Ensure start is not after end
        if(start_date_val > end_date_val) start_date_val <- first(dates)
      }
      dateRangeInput("date_range", label = "Select Date Range", start = start_date_val, end = end_date_val, min = first(dates), max = last(dates))
    } else { NULL }
  })
  
  # --- Data Loading Reactives ---
  selected_files_base <- reactive({
    info <- req(all_processed_files_info())
    # Ensure inputs are valid before proceeding
    req(input$experiment, input$experiment != "")
    req(input$cohort, input$cohort != "")
    req(input$rat, input$rat != "")
    req(input$date_choice)
    req(nrow(info) > 0)
    
    # Filter based on experiment, cohort, rat
    filtered_info <- info[experiment_id == input$experiment & cohort_id == input$cohort & rat_id == input$rat, ]
    req(nrow(filtered_info) > 0, cancelOutput = FALSE, message = "No files found for Experiment/Cohort/Rat selection.") # Provide feedback if needed
    
    # Filter by Date
    if (input$date_choice == "single") {
      req(input$single_date); selected_date <- ymd(input$single_date, quiet=TRUE); req(!is.na(selected_date))
      filtered_info <- filtered_info[date == selected_date, ]
    } else if (input$date_choice == "range") {
      req(input$date_range); start_date <- ymd(input$date_range[1], quiet=TRUE); end_date <- ymd(input$date_range[2], quiet=TRUE); req(!is.na(start_date), !is.na(end_date))
      # Ensure date range is inclusive
      filtered_info <- filtered_info[date >= start_date & date <= end_date, ]
    }
    # If 'all' dates, no further date filtering is needed here
    
    if(nrow(filtered_info) == 0){ showNotification("No processed files found for the selected criteria (including date).", type="warning") }
    req(nrow(filtered_info) > 0, cancelOutput = FALSE) # Need files to proceed
    return(filtered_info)
  })
  
  # Helper function to read selected files
  load_selected_files <- function(file_type_short) {
    # This function remains largely the same, but now gets file paths directly
    base_info <- selected_files_base() # This now contains direct file paths
    req(nrow(base_info) > 0)
    
    files_to_load_info <- base_info[file_type == file_type_short, ]
    req(nrow(files_to_load_info) > 0, cancelOutput = FALSE)
    
    files_to_load <- files_to_load_info$file_path # Get paths from manifest data
    
    files_exist <- file.exists(files_to_load)
    if(!any(files_exist)){
      showNotification(paste("Manifest lists", length(files_to_load), file_type_short, "file(s), but none exist on disk for this selection."), type="error")
      return(data.table())
    }
    if(!all(files_exist)) {
      warning("Manifest lists ", length(files_to_load), " ", file_type_short, " files, but only ", sum(files_exist), " found on disk.")
      files_to_load <- files_to_load[files_exist]
    }
    
    message(">>> Reading ", length(files_to_load), " '", file_type_short, "' file(s) from disk (or cache miss)... paths from manifest.")
    
    tryCatch({
      # fread can handle multiple files directly if needed, but lapply is fine
      data_list <- lapply(files_to_load, function(f) {
        dt <- data.table::fread(f)
        # Add source filename for debugging if needed
        # dt[, source_file := basename(f)]
        return(dt)
      })
      combined_data <- data.table::rbindlist(data_list, fill = TRUE, use.names=TRUE) # Use names robustly
      
      # --- Type Conversion (Important after reading CSV) ---
      time_cols <- intersect(c("Timestamp", "BinStartTime"), names(combined_data))
      for(t_col in time_cols){
        if(!lubridate::is.POSIXct(combined_data[[t_col]])) {
          # Try parsing common formats, assuming UTC write from processing script
          # fwrite with dateTimeAs="write.csv" usually writes YYYY-MM-DD HH:MM:SS
          original_class <- class(combined_data[[t_col]])[1]
          message(paste("Converting column", t_col, "(class:", original_class ,") to POSIXct..."))
          converted_time <- lubridate::parse_date_time(combined_data[[t_col]],
                                                       orders = c("Ymd HMS", "Ymd HM", "Ymd"), tz="UTC", quiet=TRUE)
          
          # Check if conversion failed substantially
          na_frac <- sum(is.na(converted_time)) / length(converted_time)
          if(na_frac > 0.1) { # Allow a small fraction of NAs perhaps
            warning("High proportion (", round(na_frac*100), "%) of NAs after converting '", t_col, "' to POSIXct.")
          }
          combined_data[, (t_col) := converted_time]
        }
      }
      # Convert Count columns back to integer if read as numeric/character
      count_col_names_in_data <- grep("^Count_", names(combined_data), value=TRUE)
      for(c_col in count_col_names_in_data){ if(!is.integer(combined_data[[c_col]])){ combined_data[, (c_col) := as.integer(get(c_col))] }}
      # Convert Duration columns back to numeric if read as character
      duration_col_names_in_data <- grep("^TotalDuration_", names(combined_data), value=TRUE)
      for(d_col in duration_col_names_in_data){ if(!is.numeric(combined_data[[d_col]])){ combined_data[, (d_col) := as.numeric(get(d_col))] }}
      # Convert Wheel_Movement if read as character
      if("Wheel_Movement" %in% names(combined_data) && !is.numeric(combined_data$Wheel_Movement)){ combined_data[, Wheel_Movement := as.numeric(Wheel_Movement)] }
      # --- End Type Conversion ---
      
      
      # Order by time if column exists
      time_col_to_order <- intersect(c("Timestamp", "BinStartTime"), names(combined_data))
      if(length(time_col_to_order) > 0){
        setorderv(combined_data, time_col_to_order[1])
      }
      
      message("Loaded data dimensions for ", file_type_short, ": ", nrow(combined_data), " rows, ", ncol(combined_data), " cols.")
      return(combined_data)
    }, error = function(e) {
      showNotification(paste("Error reading/combining", file_type_short, "files:", e$message), type="error")
      return(data.table())
    })
  }
  
  
  # Cache key reactive based on selection inputs
  cache_key_inputs <- reactive({
    # This remains the same, defining the user's selection state
    list(input$experiment, input$cohort, input$rat, input$date_choice, input$single_date, input$date_range)
  })
  
  # Apply bindCache to loading reactives
  # These reactives remain the same, calling the (unchanged) load_selected_files helper
  # The caching depends on cache_key_inputs, correctly memoizing results for specific selections
  loaded_file3 <- reactive({ load_selected_files("File3") }) %>% bindCache(cache_key_inputs())
  loaded_file6 <- reactive({ load_selected_files("File6") }) %>% bindCache(cache_key_inputs())
  loaded_file7 <- reactive({ load_selected_files("File7") }) %>% bindCache(cache_key_inputs()) # Still loaded even if not used in UI
  loaded_file8 <- reactive({ load_selected_files("File8") }) %>% bindCache(cache_key_inputs())
  loaded_wheel <- reactive({ load_selected_files("WheelMovement") }) %>% bindCache(cache_key_inputs())
  
  # --- Render Outputs ---
  # NO CHANGES needed here - rely on the loaded_fileX reactives
  
  # == Plotting Tabs ==
  output$daily_plots_output <- renderPlot({
    data_daily <- loaded_file8()
    validate(need(nrow(data_daily) > 0, "No daily summary data (File 8) available for this selection."))
    
    # Ensure BinStartTime is Date type for plotting axis
    if (nrow(data_daily) > 0 && !inherits(data_daily$BinStartTime, "Date")) {
      data_daily[, BinStartTime := as.Date(BinStartTime)]
    }
    validate(need(inherits(data_daily$BinStartTime, "Date"), "BinStartTime in File 8 could not be converted to Date."))
    
    
    plot_cols <- intersect(COUNT_COL_NAMES, names(data_daily)) # Only plot count cols that exist
    validate(need(length(plot_cols) > 0, "No 'Count_*' columns found in File 8 data."))
    
    # Use data.table::melt for efficiency
    data_long <- tryCatch(melt(data_daily, id.vars = "BinStartTime", measure.vars = plot_cols, variable.name = "Label", value.name = "Count", na.rm=TRUE), error=function(e) NULL)
    validate(need(!is.null(data_long) && nrow(data_long) > 0, "Failed to reshape File 8 data for plotting."))
    
    data_long[, Label := gsub("Count_", "", Label)] # Clean label name
    
    # Determine reasonable date breaks based on range
    date_range_days <- as.numeric(diff(range(data_long$BinStartTime, na.rm=TRUE)))
    date_break_setting <- if(is.na(date_range_days) || date_range_days <= 7) { "1 day" }
    else if (date_range_days <= 60) { "1 week" }
    else if (date_range_days <= 365) { "1 month"}
    else { "3 months"}
    date_label_format <- if(date_range_days <= 90) { "%m-%d"} else {"%Y-%m"}
    
    ggplot(data_long, aes(x = BinStartTime, y = Count)) +
      geom_col(fill = "steelblue") +
      facet_wrap(~ Label, scales = "free_y", ncol = 4) +
      labs(title = "Total Daily Beambreak Counts per Channel", x = "Date", y = "Total Count") +
      theme_bw(base_size = 10) +
      theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=8), # Adjust angle/size
            strip.text = element_text(size = 8)) + # Smaller facet titles
      scale_x_date(date_breaks = date_break_setting, date_labels = date_label_format)
  }, height=600) # Set height in ui or here
  
  # == Table Tabs ==
  output$tbl_minute <- DT::renderDataTable({
    data <- loaded_file6()
    validate(need(nrow(data) > 0, "No minute bin data (File 6) available for this selection."))
    # Ensure BinStartTime is POSIXct for display formatting options
    if(!"POSIXct" %in% class(data$BinStartTime)) data[, BinStartTime := as.POSIXct(BinStartTime, origin="1970-01-01", tz="UTC")]
    # Format time for display if desired
    # data_display <- copy(data)[, BinStartTime := format(BinStartTime, "%Y-%m-%d %H:%M")]
    datatable(data, options = list(pageLength = 15, scrollX = TRUE, searchDelay = 500), rownames = FALSE, filter = 'top')
  }, server = TRUE) # Enable server-side processing
  
  output$tbl_raw_states <- DT::renderDataTable({
    data <- loaded_file3()
    validate(need(nrow(data) > 0, "No raw states data (File 3) available for this selection."))
    cols_to_show <- intersect(c("Timestamp", "DigitalPins_Raw", paste0("Channel_", 0:7)), names(data))
    validate(need(length(cols_to_show) > 2, "Required columns not found in File 3."))
    # Ensure Timestamp is POSIXct
    if(!"POSIXct" %in% class(data$Timestamp)) data[, Timestamp := as.POSIXct(Timestamp, origin="1970-01-01", tz="UTC")]
    # Format time for display if desired
    # data_display <- copy(data)[, Timestamp := format(Timestamp, "%Y-%m-%d %H:%M:%OS3")]
    datatable(data[, ..cols_to_show], options = list(pageLength = 15, scrollX = TRUE, searchDelay = 500), rownames = FALSE, filter = 'top')
  }, server = TRUE) # Enable server-side processing
  
  output$tbl_wheel <- DT::renderDataTable({
    data <- loaded_wheel()
    validate(need(nrow(data) > 0, "No wheel movement data available for this selection."))
    # Ensure Timestamp is POSIXct
    if(!"POSIXct" %in% class(data$Timestamp)) data[, Timestamp := as.POSIXct(Timestamp, origin="1970-01-01", tz="UTC")]
    # Format time for display if desired
    # data_display <- copy(data)[, Timestamp := format(Timestamp, "%Y-%m-%d %H:%M:%OS3")]
    datatable(data, options = list(pageLength = 15, scrollX = TRUE, searchDelay = 500), rownames = FALSE, filter = 'top')
    # No server=TRUE unless WheelMovement files are expected to be huge
  })
  
  # --- Download Handlers ---
  # These remain the same, using the cached reactive data
  output$download_minute <- downloadHandler(
    filename = function() { paste0("minute_binned_data_", input$experiment, "_", input$cohort, "_", input$rat, "_", Sys.Date(), ".csv") },
    content = function(file) { data.table::fwrite(loaded_file6(), file) } # Use fwrite for download
  )
  output$download_file3 <- downloadHandler(
    filename = function() { paste0("raw_states_file3_", input$experiment, "_", input$cohort, "_", input$rat, "_", Sys.Date(), ".csv") },
    content = function(file) { data.table::fwrite(loaded_file3(), file) } # Use fwrite for download
  )
  output$download_wheel <- downloadHandler(
    filename = function() { paste0("wheel_movement_", input$experiment, "_", input$cohort, "_", input$rat, "_", Sys.Date(), ".csv") },
    content = function(file) { data.table::fwrite(loaded_wheel(), file) } # Use fwrite for download
  )
  
} # End Server Function

# --- Run the Shiny App ---
shinyApp(ui = ui, server = server)